import { ReturnProduct } from '../models/return_product.model';

export const RETURN_PRODUCTS: ReturnProduct[] = [
  {
    supplier_id: 4641,
    supplier_name: '欣臨企業股份有限公司',
    product_id: '5500126',
    product_name: 'Lysol《來舒》衣物殺菌劑 (1000ml)',
    return_reason: '價格太貴',
    frequency: 648,
  },
  {
    supplier_id: 6330,
    supplier_name: '寶康行銷股份有限公司',
    product_id: '1891334',
    product_name: '寶礦力水得15g粉末包裝',
    return_reason: '拒收',
    frequency: 520,
  },
  {
    supplier_id: 4891,
    supplier_name: '依聯工業股份有限公司',
    product_id: '1173763',
    product_name: '依必朗濃縮抗菌防蹣洗衣乳(清香補充包)2000ml',
    return_reason: '其他',
    frequency: 169,
  },
  {
    supplier_id: 4641,
    supplier_name: '欣臨企業股份有限公司',
    product_id: '5188673',
    product_name: '1元加購《阿華田》經典原味(650g)',
    return_reason: '拒收',
    frequency: 144,
  },
  {
    supplier_id: 1481,
    supplier_name: '新禾科技興業股份有限公司',
    product_id: '6198726',
    product_name: 'TOSHIBA 原廠黑色有線滑鼠',
    return_reason: '規格/尺寸不符所需',
    frequency: 134,
  },
  {
    supplier_id: 4891,
    supplier_name: '依聯工業股份有限公司',
    product_id: '5957085',
    product_name: '依必朗防霉抗菌洗衣精-陽光香氛(4000gx4瓶)/箱',
    return_reason: '拒收',
    frequency: 128,
  },
  {
    supplier_id: 4948,
    supplier_name: '正暉股份有限公司',
    product_id: '5544045',
    product_name: '《明治》明治Pupurun雙層夾餡軟糖-汽水口味',
    return_reason: '拒收',
    frequency: 110,
  },
  {
    supplier_id: 4948,
    supplier_name: '正暉股份有限公司',
    product_id: '5435621',
    product_name: '《明治》明治Pupurun雙層夾餡軟糖-葡萄口味',
    return_reason: '拒收',
    frequency: 110,
  },
  {
    supplier_id: 1481,
    supplier_name: '新禾科技興業股份有限公司',
    product_id: '5728432',
    product_name: '4GB DDR3 記憶體【需自行安裝】',
    return_reason: '規格/尺寸不符所需',
    frequency: 104,
  },
  {
    supplier_id: 4556,
    supplier_name: '金品行銷有限公司',
    product_id: '5044849',
    product_name: '《彼得兔》如意原味蛋捲經典禮盒(432g)',
    return_reason: '重訂(改買別款.改付款方式等)',
    frequency: 100,
  },
];
