import { CancelProduct } from '../models/cancel_product.model';

export const CANCEL_PRODUCTS: CancelProduct[] = [
  {
    supplier_id: 8297,
    supplier_name: '汰芮國際有限公司',
    product_id: '5399324',
    product_name: '【TAIREI 】清新晨露洗衣精補充包2000ml',
    cancel_reason: '取消-轉單前訂購單已取消\t',
    frequency: 48,
  },
  {
    supplier_id: 8297,
    supplier_name: '汰芮國際有限公司',
    product_id: '5290107',
    product_name: 'Living type白麝香潔膚濕紙巾(10抽x3包入)',
    cancel_reason: '取消-轉單前訂購單已取消\t',
    frequency: 48,
  },
  {
    supplier_id: 5192,
    supplier_name: '掬水軒食品股份有限公司',
    product_id: '3199602',
    product_name: '《掬水軒》迷你口糧棒(70g)',
    cancel_reason: '取消-缺貨',
    frequency: 36,
  },
  {
    supplier_id: 4684,
    supplier_name: '喜威世流通股份有限公司',
    product_id: '5549917',
    product_name: '《泰山》纖?輕餐- 蒟蒻燕麥(3罐/組)',
    cancel_reason: '取消-缺貨',
    frequency: 24,
  },
  {
    supplier_id: 4280,
    supplier_name: '脫普聚益股份有限公司',
    product_id: '5896803',
    product_name: '〔贈品〕妙潔垢乾淨去污擦',
    cancel_reason: '取消-轉單前訂購單已取消\t',
    frequency: 24,
  },
  {
    supplier_id: 6401,
    supplier_name: '開元食品工業股份有限公司',
    product_id: '1919393',
    product_name: '《戀》奶球B (10CCx50入)',
    cancel_reason: '取消-缺貨',
    frequency: 24,
  },
  {
    supplier_id: 5148,
    supplier_name: '巧幫手實業有限公司',
    product_id: '3643088',
    product_name: '巧幫手一試靈肥皂草洗衣粉(600g)',
    cancel_reason: '取消-轉單前訂購單已取消\t',
    frequency: 22,
  },
  {
    supplier_id: 8653,
    supplier_name: '新松國際股份有限公司',
    product_id: '5273409',
    product_name: '《新松》義大利麵醬-羅勤青醬(240g)',
    cancel_reason: '取消-缺貨',
    frequency: 22,
  },
  {
    supplier_id: 8995,
    supplier_name: '花仙子企業股份有限公司',
    product_id: '5954697',
    product_name: '克潮靈集水袋補充包-玫瑰香(400mlx3入)',
    cancel_reason: '取消-缺貨',
    frequency: 20,
  },
  {
    supplier_id: 8297,
    supplier_name: '汰芮國際有限公司',
    product_id: '5549659',
    product_name: '【LIVIN ’CARE】法國澄花菁萃芳香噴霧(250ml)',
    cancel_reason: '取消-轉單前訂購單已取消\t',
    frequency: 20,
  },
];
